name    'tscopp-zabbixserver'
version '0.1.0'
source 'UNKNOWN'
author 'tscopp'
license 'Apache License, Version 2.0'
summary 'Zabbixserver module'
description 'Module to install zabbixserver'
project_page 'https://github.com/tscopp/puppet-zabbixserver'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
